// Generated by CoffeeScript 1.7.1
(function() {
  define(['chai', 'backbone', 'backbone-dom-view'], function(_arg, Backbone, DomView) {
    var expect, model;
    expect = _arg.expect;
    model = null;
    beforeEach(function() {
      return model = new Backbone.Model();
    });
    return describe('connect helper', function() {
      return it('should bind prop and field', function() {
        var View, el, view;
        View = DomView.extend({
          template: {
            '': {
              connect: {
                'id|click': 'id'
              }
            }
          }
        });
        model.set('id', 'test');
        view = new View(model);
        el = view.$el;
        expect(el).to.have.prop('id', 'test');
        el.prop('id', 'max');
        el.click();
        expect(model.get('id')).to.be.equal('max');
        model.set('id', 'bob');
        return expect(el).to.have.prop('id', 'bob');
      });
    });
  });

}).call(this);
