// Generated by LiveScript 1.2.0
(function(){
  define(['chai', 'backbone', 'dom-view'], function(chai, Backbone, DomView){
    var expect;
    expect = chai.expect;
    return describe('DOMView', function(){
      var model;
      model = null;
      beforeEach(function(){
        return model = new Backbone.Model();
      });
      describe('class helper', function(){
        it('should toggle class for model events', function(){
          var View, view, el;
          View = DomView.extend({
            template: {
              '': {
                'class': {
                  'test': 'test eventName'
                }
              }
            }
          });
          view = new View(model);
          el = view.$el;
          expect(el).not.to.have['class']('test');
          model.trigger('test', true);
          expect(el).to.have['class']('test');
          model.trigger('eventName', false);
          expect(el).not.to.have['class']('test');
        });
        it('should toggle class for model events with changed arg number |arg(1)', function(){
          var View, view, el;
          View = DomView.extend({
            template: {
              '': {
                'class': {
                  'test': 'test|arg(1) eventName|arg(2)'
                }
              }
            }
          });
          view = new View(model);
          el = view.$el;
          expect(el).not.to.have['class']('test');
          model.trigger('test', false, true);
          expect(el).to.have['class']('test');
          model.trigger('eventName', true, true, false);
          expect(el).not.to.have['class']('test');
        });
        it('should toggle class for model field @fieldName', function(){
          var View, view, el;
          View = DomView.extend({
            template: {
              '': {
                'class': {
                  'test': '@test'
                }
              }
            }
          });
          model.set('test', true);
          view = new View(model);
          el = view.$el;
          expect(el).to.have['class']('test');
          model.set('test', false);
          expect(el).not.to.have['class']('test');
          model.set('test', true);
          expect(el).to.have['class']('test');
        });
        it('should toggle class for view event #viewEvent', function(){
          var View, view, el;
          View = DomView.extend({
            template: {
              '': {
                'class': {
                  'test': '#test #eventName|arg(1)'
                }
              }
            }
          });
          view = new View;
          el = view.$el;
          expect(el).not.to.have['class']('test');
          view.trigger('test', true);
          expect(el).to.have['class']('test');
          view.trigger('eventName', true, false);
          expect(el).not.to.have['class']('test');
        });
        it('should toggle class for function', function(){
          var View, view, el;
          View = DomView.extend({
            template: {
              '': {
                'class': {
                  'test': {
                    'test': function(){
                      return this.model.get('field');
                    }
                  }
                }
              }
            }
          });
          view = new View(model);
          el = view.$el;
          expect(el).not.to.have['class']('test');
          model.set('field', 1);
          model.trigger('test');
          expect(el).to.have['class']('test');
          model.set('field', '');
          model.trigger('test');
          expect(el).not.to.have['class']('test');
        });
      });
    });
  });
}).call(this);
